apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: test
  namespace: default
spec:
  replicas: 5
  solrImage:
    tag: "8.3"
  solrJavaMem: "-Xms500m -Xmx500m"
  solrAddressability:
    external:
      method: Ingress
      domainName: "minikube"
      useExternalAddress: true
  customSolrKubeOptions:
    ingressOptions:
      annotations:
        'nginx.ingress.kubernetes.io/default-backend': test-solrcloud-common
